project_id = "ahakqntfpkbeblmljeib"

[functions.delete-account]
verify_jwt = false

[functions.validate-receipt]
verify_jwt = false

[functions.healing-guide]
verify_jwt = false

[functions.crm-data]
verify_jwt = false